spring:
  application:
    name: config-server
server:
  port: 8767


spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hblutao1988/springcloud-config
		  searchPaths: respo
		  username: hblutao1988
		  password: kiss527131407
      label: master
spring.application.name=config-client
spring.cloud.config.server.git.searchPaths=respo2
spring.cloud.config.server.git.searchPaths=respo4